### ISSUE TITLE
Consider add npm sudo

### ISSUE THREAD

**Issue by zooeywm** [TD-Sky/iwant#1]
https://github.com/TD-Sky/iwant/blob/05f92ca0d416f02d780c9b2c895b42bdbff8f7d1/package-managers/src/npm.rs#L9

Some items need `sudo`

**Comment by TD-Sky** [comment]
I'm using `npm` provided by [fnm](https://github.com/Schniz/fnm), which need no root permission.

If you wanna install with `/usr/bin/npm`, please use `sudo iwant`.
